---

- name: Install nginx
  yum:
    name:
      - nginx
    state: latest

- name: Create document in directory
  file:
    state: directory
    path: /var/www/jrguez_conf_page
    owner: root
    group: root
    mode: 0755

- name: Copy index.html in directory
  copy: 
    src: index.html
    dest: /var/www/jrguez_conf_page
    owner: root
    group: root
    mode: 0644

- name: Start and enable nginx service
  service:
    name: nginx
    state: started
    enabled: yes

